---
- name: reload_bird
  shell:
    cmd: "birdc configure || systemctl start bird; birdc configure"
- name: reload_bird6
  shell:
    cmd: "birdc6 configure || systemctl start bird6; birdc6 configure"
